kind: Service
apiVersion: v1
metadata:
  name: landing-service
  namespace: production
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  #type: LoadBalancer
  selector:
    app: landing
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: landing-deployment
  namespace: production
spec:
  selector:
    matchLabels:
      app: landing
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
      - name: landing
        image: farman17/dekkeng-landing
        ports:
        - containerPort: 80
        imagePullPolicy: "Always"

---
kind: ConfigMap
metadata:
  labels:
    app: landing
  name: nginx-conf
data:
  site.conf: |
    server {
      listen 443 ssl;
      server_name landing.dailybugis.my.id;
      ssl_certificate /run/secrets/nginx-cert/tls.crt;
      ssl_certificate_key /run/secrets/nginx-cert/tls.key;
      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
      }
    }
    
    
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: landing-ingress
  namespace: production
  annotations:
    ingress.kubernetes.io/proxy-body-size: 4m
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-secret: "NAMESPACE/landing-tls"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "true"
spec:
  rules:
  - host: landing.dailybugis.my.id
    http:
      paths:
      #- path: /
      - backend:
          serviceName: landing-service
          servicePort: 443
