apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-server
  name: node-svc
  namespace: production

spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: node-server
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: node-ingress
  namespace: production
spec:
  tls:
  - hosts:
    - landing.dailybugis.my.id
    secretName: tls-secret
  rules:
  - host: landing.dailybugis.my.id
    http:
      paths:
      - backend:
          serviceName: node-svc
          servicePort: 8080
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: landing-deployment
  namespace: production
spec:
  selector:
    matchLabels:
      app: node-server
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
      - name: landing
        image: farman17/dekkeng-landing
        ports:
        - containerPort: 80
        imagePullPolicy: "Always"

