apiVersion: apps/v1
kind: Deployment
metadata:
  name: dekkeng-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deks
  template:
    metadata:
      labels:
        app: deks
    spec:
      containers:
      - name: dekkeng-container
        image: farman17/dekkeng-landing
---
apiVersion: v1
kind: Service
metadata:
  name: dekkeng-service
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: deks
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dekkeng-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: 192.168.33.14
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dekkeng-service
            port:
              number: 80
