kind: Service
apiVersion: v1
metadata:
  name: landing-service
  namespace: production
spec:
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
  type: LoadBalancer
  selector:
    app: landing
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: landing-deployment
  namespace: production
spec:
  selector:
    matchLabels:
      app: landing
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
      - name: landing
        image: farman17/dekkeng-landing
        ports:
        - containerPort: 80
        imagePullPolicy: "Always"
